//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "podSettings"
	/// <summary>Pod Settings</summary>
	public partial interface IPodSettings : IPublishedElement
	{
		/// <summary>Border Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyColor BorderColor { get; }

		/// <summary>Fill Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyGradient FillGradient { get; }

		/// <summary>Icon Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyColor IconColor { get; }
	}

	/// <summary>Pod Settings</summary>
	[PublishedModel("podSettings")]
	public partial class PodSettings : PublishedElementModel, IPodSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "podSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PodSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PodSettings(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Border Color: Color around the icon.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("borderColor")]
		public Amplify.Web.Custom.Models.AmplifyColor BorderColor => GetBorderColor(this);

		/// <summary>Static getter for Border Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyColor GetBorderColor(IPodSettings that) => that.Value<Amplify.Web.Custom.Models.AmplifyColor>("borderColor");

		///<summary>
		/// Fill Gradient: Fill gradient around the icon.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("fillGradient")]
		public Amplify.Web.Custom.Models.AmplifyGradient FillGradient => GetFillGradient(this);

		/// <summary>Static getter for Fill Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyGradient GetFillGradient(IPodSettings that) => that.Value<Amplify.Web.Custom.Models.AmplifyGradient>("fillGradient");

		///<summary>
		/// Icon Color: Pick the icon color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("iconColor")]
		public Amplify.Web.Custom.Models.AmplifyColor IconColor => GetIconColor(this);

		/// <summary>Static getter for Icon Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyColor GetIconColor(IPodSettings that) => that.Value<Amplify.Web.Custom.Models.AmplifyColor>("iconColor");
	}
}
