//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "alert"
	/// <summary>Sitewide Alert</summary>
	public partial interface IAlert : IPublishedElement
	{
		/// <summary>Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyColor AlertBgColor { get; }

		/// <summary>Background Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyGradient AlertBgGradient { get; }

		/// <summary>Alert Content</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		IHtmlString AlertContent { get; }

		/// <summary>Is Enabled</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		bool AlertEnabled { get; }

		/// <summary>Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyColor AlertTextColor { get; }

		/// <summary>Alert</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string AlertTitle { get; }

		/// <summary>Buttons</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		IEnumerable<FaLinksPropertyEditor.Models.FaLink> Buttons { get; }
	}

	/// <summary>Sitewide Alert</summary>
	[PublishedModel("alert")]
	public partial class Alert : PublishedElementModel, IAlert
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "alert";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Alert, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Alert(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Background Color: Set the background color for the alert notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertBgColor")]
		public Amplify.Web.Custom.Models.AmplifyColor AlertBgColor => GetAlertBgColor(this);

		/// <summary>Static getter for Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyColor GetAlertBgColor(IAlert that) => that.Value<Amplify.Web.Custom.Models.AmplifyColor>("alertBgColor");

		///<summary>
		/// Background Gradient: Add background gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertBgGradient")]
		public Amplify.Web.Custom.Models.AmplifyGradient AlertBgGradient => GetAlertBgGradient(this);

		/// <summary>Static getter for Background Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyGradient GetAlertBgGradient(IAlert that) => that.Value<Amplify.Web.Custom.Models.AmplifyGradient>("alertBgGradient");

		///<summary>
		/// Alert Content: Optional, additional alert content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertContent")]
		public IHtmlString AlertContent => GetAlertContent(this);

		/// <summary>Static getter for Alert Content</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IHtmlString GetAlertContent(IAlert that) => that.Value<IHtmlString>("alertContent");

		///<summary>
		/// Is Enabled
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertEnabled")]
		public bool AlertEnabled => GetAlertEnabled(this);

		/// <summary>Static getter for Is Enabled</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static bool GetAlertEnabled(IAlert that) => that.Value<bool>("alertEnabled");

		///<summary>
		/// Text Color: Set text color for the alert notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertTextColor")]
		public Amplify.Web.Custom.Models.AmplifyColor AlertTextColor => GetAlertTextColor(this);

		/// <summary>Static getter for Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyColor GetAlertTextColor(IAlert that) => that.Value<Amplify.Web.Custom.Models.AmplifyColor>("alertTextColor");

		///<summary>
		/// Alert: Alert Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertTitle")]
		public string AlertTitle => GetAlertTitle(this);

		/// <summary>Static getter for Alert</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetAlertTitle(IAlert that) => that.Value<string>("alertTitle");

		///<summary>
		/// Buttons
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttons")]
		public IEnumerable<FaLinksPropertyEditor.Models.FaLink> Buttons => GetButtons(this);

		/// <summary>Static getter for Buttons</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IEnumerable<FaLinksPropertyEditor.Models.FaLink> GetButtons(IAlert that) => that.Value<IEnumerable<FaLinksPropertyEditor.Models.FaLink>>("buttons");
	}
}
