//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Application Configuration</summary>
	[PublishedModel("appConfig")]
	public partial class AppConfig : PublishedContentModel, IAdminEmailSettings, IAlert, IAnalytics, IContactDetails, ICookieNotification, ISite
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "appConfig";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AppConfig, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AppConfig(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Twitter Username: Add your twitter username, used in the share links.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("twitterUsername")]
		public string TwitterUsername => this.Value<string>("twitterUsername");

		///<summary>
		/// Admin Email: The site administrator email address.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("adminEmail")]
		public string AdminEmail => AdminEmailSettings.GetAdminEmail(this);

		///<summary>
		/// Admin Email Sender Name: The email sender name used for admin emails.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("adminEmailSenderName")]
		public string AdminEmailSenderName => AdminEmailSettings.GetAdminEmailSenderName(this);

		///<summary>
		/// Background Color: Set the background color for the alert notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertBgColor")]
		public Amplify.Web.Custom.Models.AmplifyColor AlertBgColor => Alert.GetAlertBgColor(this);

		///<summary>
		/// Background Gradient: Add background gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertBgGradient")]
		public Amplify.Web.Custom.Models.AmplifyGradient AlertBgGradient => Alert.GetAlertBgGradient(this);

		///<summary>
		/// Alert Content: Optional, additional alert content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertContent")]
		public IHtmlString AlertContent => Alert.GetAlertContent(this);

		///<summary>
		/// Is Enabled
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertEnabled")]
		public bool AlertEnabled => Alert.GetAlertEnabled(this);

		///<summary>
		/// Text Color: Set text color for the alert notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertTextColor")]
		public Amplify.Web.Custom.Models.AmplifyColor AlertTextColor => Alert.GetAlertTextColor(this);

		///<summary>
		/// Alert: Alert Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("alertTitle")]
		public string AlertTitle => Alert.GetAlertTitle(this);

		///<summary>
		/// Buttons
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttons")]
		public IEnumerable<FaLinksPropertyEditor.Models.FaLink> Buttons => Alert.GetButtons(this);

		///<summary>
		/// Analytics Code: Enter your js tracking analytics tracking code,
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("analyticsCode")]
		public string AnalyticsCode => Analytics.GetAnalyticsCode(this);

		///<summary>
		/// Address 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("address1")]
		public string Address1 => ContactDetails.GetAddress1(this);

		///<summary>
		/// Address 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("address2")]
		public string Address2 => ContactDetails.GetAddress2(this);

		///<summary>
		/// City
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("city")]
		public string City => ContactDetails.GetCity(this);

		///<summary>
		/// Country
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("country")]
		public string Country => ContactDetails.GetCountry(this);

		///<summary>
		/// Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("email")]
		public string Email => ContactDetails.GetEmail(this);

		///<summary>
		/// Post / Zip Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("postZipCode")]
		public string PostZipCode => ContactDetails.GetPostZipCode(this);

		///<summary>
		/// Region
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("region")]
		public string Region => ContactDetails.GetRegion(this);

		///<summary>
		/// Telephone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("telephone")]
		public string Telephone => ContactDetails.GetTelephone(this);

		///<summary>
		/// Town
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("town")]
		public string Town => ContactDetails.GetTown(this);

		///<summary>
		/// Background Color: Set the background color for the cookie notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bgColor")]
		public Amplify.Web.Custom.Models.AmplifyColor BgColor => CookieNotification.GetBgColor(this);

		///<summary>
		/// Button Color: Pick button color.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttonColor")]
		public Amplify.Web.Custom.Models.AmplifyColor ButtonColor => CookieNotification.GetButtonColor(this);

		///<summary>
		/// Button Text: Set the button text for closing the notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttonText")]
		public string ButtonText => CookieNotification.GetButtonText(this);

		///<summary>
		/// Cookie Text: Set the text for the cookie notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cookieText")]
		public IHtmlString CookieText => CookieNotification.GetCookieText(this);

		///<summary>
		/// Cookie Title: Set the title for cookie notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cookieTitle")]
		public string CookieTitle => CookieNotification.GetCookieTitle(this);

		///<summary>
		/// Is Enabled: Enable the cookie / privacy policy notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isEnabled")]
		public bool IsEnabled => CookieNotification.GetIsEnabled(this);

		///<summary>
		/// Text Color: Set text color for the cookie notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("textColor")]
		public Amplify.Web.Custom.Models.AmplifyColor TextColor => CookieNotification.GetTextColor(this);

		///<summary>
		/// Short Description: Add a short description of your site, used where required.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription => Site.GetShortDescription(this);

		///<summary>
		/// Site Name: App name for use in email templates and across the site.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("siteName")]
		public string SiteName => Site.GetSiteName(this);

		///<summary>
		/// Theme: Choose your app theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("theme")]
		public IPublishedContent Theme => Site.GetTheme(this);
	}
}
