//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "cookieNotification"
	/// <summary>Cookie Notification</summary>
	public partial interface ICookieNotification : IPublishedElement
	{
		/// <summary>Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyColor BgColor { get; }

		/// <summary>Button Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyColor ButtonColor { get; }

		/// <summary>Button Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string ButtonText { get; }

		/// <summary>Cookie Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		IHtmlString CookieText { get; }

		/// <summary>Cookie Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		string CookieTitle { get; }

		/// <summary>Is Enabled</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		bool IsEnabled { get; }

		/// <summary>Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		Amplify.Web.Custom.Models.AmplifyColor TextColor { get; }
	}

	/// <summary>Cookie Notification</summary>
	[PublishedModel("cookieNotification")]
	public partial class CookieNotification : PublishedElementModel, ICookieNotification
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "cookieNotification";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CookieNotification, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CookieNotification(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Background Color: Set the background color for the cookie notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bgColor")]
		public Amplify.Web.Custom.Models.AmplifyColor BgColor => GetBgColor(this);

		/// <summary>Static getter for Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyColor GetBgColor(ICookieNotification that) => that.Value<Amplify.Web.Custom.Models.AmplifyColor>("bgColor");

		///<summary>
		/// Button Color: Pick button color.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttonColor")]
		public Amplify.Web.Custom.Models.AmplifyColor ButtonColor => GetButtonColor(this);

		/// <summary>Static getter for Button Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyColor GetButtonColor(ICookieNotification that) => that.Value<Amplify.Web.Custom.Models.AmplifyColor>("buttonColor");

		///<summary>
		/// Button Text: Set the button text for closing the notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttonText")]
		public string ButtonText => GetButtonText(this);

		/// <summary>Static getter for Button Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetButtonText(ICookieNotification that) => that.Value<string>("buttonText");

		///<summary>
		/// Cookie Text: Set the text for the cookie notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cookieText")]
		public IHtmlString CookieText => GetCookieText(this);

		/// <summary>Static getter for Cookie Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IHtmlString GetCookieText(ICookieNotification that) => that.Value<IHtmlString>("cookieText");

		///<summary>
		/// Cookie Title: Set the title for cookie notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cookieTitle")]
		public string CookieTitle => GetCookieTitle(this);

		/// <summary>Static getter for Cookie Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static string GetCookieTitle(ICookieNotification that) => that.Value<string>("cookieTitle");

		///<summary>
		/// Is Enabled: Enable the cookie / privacy policy notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isEnabled")]
		public bool IsEnabled => GetIsEnabled(this);

		/// <summary>Static getter for Is Enabled</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static bool GetIsEnabled(ICookieNotification that) => that.Value<bool>("isEnabled");

		///<summary>
		/// Text Color: Set text color for the cookie notification.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("textColor")]
		public Amplify.Web.Custom.Models.AmplifyColor TextColor => GetTextColor(this);

		/// <summary>Static getter for Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static Amplify.Web.Custom.Models.AmplifyColor GetTextColor(ICookieNotification that) => that.Value<Amplify.Web.Custom.Models.AmplifyColor>("textColor");
	}
}
