//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Main Nav</summary>
	[PublishedModel("nav")]
	public partial class Nav : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "nav";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Nav, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Nav(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Enable Search
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("enableSearch")]
		public bool EnableSearch => this.Value<bool>("enableSearch");

		///<summary>
		/// Navbar End
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("endBlocks")]
		public Umbraco.Core.Models.Blocks.BlockListModel EndBlocks => this.Value<Umbraco.Core.Models.Blocks.BlockListModel>("endBlocks");

		///<summary>
		/// Icon Color: Choose  the color of your icon.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("logoColor")]
		public Amplify.Web.Custom.Models.AmplifyColor LogoColor => this.Value<Amplify.Web.Custom.Models.AmplifyColor>("logoColor");

		///<summary>
		/// Icon: Use an Icon as your brand logo.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("logoIcon")]
		public FaLinksPropertyEditor.Models.FaIcon LogoIcon => this.Value<FaLinksPropertyEditor.Models.FaIcon>("logoIcon");

		///<summary>
		/// Image: Or, choose an image.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("logoImage")]
		public IPublishedContent LogoImage => this.Value<IPublishedContent>("logoImage");

		///<summary>
		/// Svg: Or, paste your svg code here.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("logoSvg")]
		public string LogoSvg => this.Value<string>("logoSvg");

		///<summary>
		/// Logo Text: Add text next to your logo.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("logoText")]
		public string LogoText => this.Value<string>("logoText");

		///<summary>
		/// Navbar Color: Pick a background color for the navigation.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("navbarColor")]
		public Amplify.Web.Custom.Models.AmplifyColor NavbarColor => this.Value<Amplify.Web.Custom.Models.AmplifyColor>("navbarColor");

		///<summary>
		/// Navbar Gradient: Optional gradient background.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("navbarGradient")]
		public Amplify.Web.Custom.Models.AmplifyGradient NavbarGradient => this.Value<Amplify.Web.Custom.Models.AmplifyGradient>("navbarGradient");

		///<summary>
		/// Navbar Start
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("startBlocks")]
		public Umbraco.Core.Models.Blocks.BlockListModel StartBlocks => this.Value<Umbraco.Core.Models.Blocks.BlockListModel>("startBlocks");
	}
}
