//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Pods List Settings</summary>
	[PublishedModel("podsListSettings")]
	public partial class PodsListSettings : PublishedElementModel, IBgColorSetting, IBgGradientSetting, IBgTextureSetting, IColumnSettingsComposition, ICustomClassComposition, IPodSettings, ITextColorSetting
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "podsListSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PodsListSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PodsListSettings(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Background Color: Set the background color.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bgColor")]
		public Amplify.Web.Custom.Models.AmplifyColor BgColor => BgColorSetting.GetBgColor(this);

		///<summary>
		/// Background Gradient
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bgGradient")]
		public Amplify.Web.Custom.Models.AmplifyGradient BgGradient => BgGradientSetting.GetBgGradient(this);

		///<summary>
		/// Background Texture: Add a background image as a texture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bgTexture")]
		public IPublishedContent BgTexture => BgTextureSetting.GetBgTexture(this);

		///<summary>
		/// Items Per Row
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("columns")]
		public string Columns => ColumnSettingsComposition.GetColumns(this);

		///<summary>
		/// Custom Class: Add custom classes.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("customClass")]
		public string CustomClass => CustomClassComposition.GetCustomClass(this);

		///<summary>
		/// Border Color: Color around the icon.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("borderColor")]
		public Amplify.Web.Custom.Models.AmplifyColor BorderColor => PodSettings.GetBorderColor(this);

		///<summary>
		/// Fill Gradient: Fill gradient around the icon.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("fillGradient")]
		public Amplify.Web.Custom.Models.AmplifyGradient FillGradient => PodSettings.GetFillGradient(this);

		///<summary>
		/// Icon Color: Pick the icon color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("iconColor")]
		public Amplify.Web.Custom.Models.AmplifyColor IconColor => PodSettings.GetIconColor(this);

		///<summary>
		/// Text Color: Set the text color.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("textColor")]
		public Amplify.Web.Custom.Models.AmplifyColor TextColor => TextColorSetting.GetTextColor(this);
	}
}
