//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Theme</summary>
	[PublishedModel("theme")]
	public partial class Theme : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "theme";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Theme, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Theme(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Background Color Palette
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("backgroundPalette")]
		public List<Amplify.Web.Custom.Models.AmplifyColor> BackgroundPalette => this.Value<List<Amplify.Web.Custom.Models.AmplifyColor>>("backgroundPalette");

		///<summary>
		/// Css Output Filename: The name of the output sass file.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cssOutputFilename")]
		public string CssOutputFilename => this.Value<string>("cssOutputFilename");

		///<summary>
		/// Google Font: Imported font code.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("googleFont")]
		public string GoogleFont => this.Value<string>("googleFont");

		///<summary>
		/// Gradient Color Palette
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("gradientPalette")]
		public List<Amplify.Web.Custom.Models.AmplifyGradient> GradientPalette => this.Value<List<Amplify.Web.Custom.Models.AmplifyGradient>>("gradientPalette");

		///<summary>
		/// Heading Font: Font stack for headings.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("primaryFont")]
		public string PrimaryFont => this.Value<string>("primaryFont");

		///<summary>
		/// Sass Input Filename: Which sass file to build.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("sassInputFilename")]
		public string SassInputFilename => this.Value<string>("sassInputFilename");

		///<summary>
		/// Body Font: Font stack for text.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("secondaryFont")]
		public string SecondaryFont => this.Value<string>("secondaryFont");

		///<summary>
		/// Text Color Palette
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("textPalette")]
		public List<Amplify.Web.Custom.Models.AmplifyColor> TextPalette => this.Value<List<Amplify.Web.Custom.Models.AmplifyColor>>("textPalette");

		///<summary>
		/// Theme Base Path: Set the base path for the theme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("themeBasePath")]
		public string ThemeBasePath => this.Value<string>("themeBasePath");

		///<summary>
		/// Theme Palette: Add the theme palette.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("themePalette")]
		public List<Amplify.Web.Custom.Models.AmplifyColor> ThemePalette => this.Value<List<Amplify.Web.Custom.Models.AmplifyColor>>("themePalette");
	}
}
